# Generated by Django 3.1.2 on 2020-10-04 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smallproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('events_name', models.CharField(max_length=50)),
                ('events_date_start', models.DateTimeField()),
                ('events_date_end', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='smallproject.event', verbose_name='Events'),
        ),
    ]
