# Generated by Django 3.1.2 on 2020-10-04 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smallproject', '0002_auto_20201004_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'default_related_name': 'user'},
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invite_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to='smallproject.department')),
                ('invited_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_invited_user', to='smallproject.user')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_user', to='smallproject.user')),
            ],
            options={
                'default_related_name': 'invitation',
            },
        ),
    ]
