# Generated by Django 3.1.2 on 2020-10-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallproject', '0004_department_privilege_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
