# Generated by Django 3.1.2 on 2020-10-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallproject', '0005_auto_20201004_2330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
